# Generated by Django 5.1.6 on 2025-02-25 04:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliacion', '0002_movimientobancario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='cuenta_destino',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='cuenta_origen',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='conciliacion.cuenta'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('DEP', 'Depósito'), ('RET', 'Retiro'), ('TRA', 'Transferencia')], default='DEP', max_length=3),
        ),
        migrations.DeleteModel(
            name='MovimientoBancario',
        ),
    ]
